### ISSUE TITLE
The delegate property should be a weak var

### ISSUE THREAD

**Issue by twobitlabs** [LiorNn/DragDropCollectionView#1]
Great work on this, been playing around with it and it's working really well. Noticed controllers were leaking while profiling and it's because the delegate property is strong:

https://github.com/LiorNn/DragDropCollectionView/blob/master/DragDropCollectionView.swift#L18

It should be:

weak var draggingDelegate: DrapDropCollectionViewDelegate?

**Comment by LiorNn** [comment]
Fixed now. Thanks for spotting this!
